import React, { useState } from 'react';
import toast from 'react-hot-toast';
import MessageDisplay from './ui/MessageDisplay';
import { useMessage } from '../hooks/useMessage';
import { getMessage } from '../utils/messages';
import { api } from '../utils/api';
import CollegeDropdown from './CollegeDropdown';

const CreateStudentModal = ({ isOpen, onClose, onStudentCreated }) => {
  const { message, showSuccess, showError, clearMessage } = useMessage();
  const [formData, setFormData] = useState({
    username: '',
    studentName: '',
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    password: '',
    institute: '',
    course: '',
    major: '',
    yearOfStudy: '',
    dob: '',
    gender: '',
    address: '',
    landmark: '',
    zipcode: '',
    city: '',
    district: '',
  });
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});

    const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
    // Clear any existing messages when user starts typing
    if (message.show) clearMessage();
  };

  const handleCollegeChange = (value) => {
    setFormData({ ...formData, institute: value });
    if (errors.institute) {
      setErrors({ ...errors, institute: '' });
    }
  };

  const validate = () => {
    const newErrors = {};
    const { username, studentName, firstName, lastName, email, phone, password, institute, course, major, yearOfStudy } = formData;

    if (!username) newErrors.username = 'Username is required.';
    if (!studentName) newErrors.studentName = 'Student Name is required.';
    if (!firstName) newErrors.firstName = 'First name is required.';
    if (!lastName) newErrors.lastName = 'Last name is required.';
    if (!institute) newErrors.institute = 'Institute is required.';
    if (!course) newErrors.course = 'Course is required.';
    if (!major) newErrors.major = 'Major is required.';
    if (!yearOfStudy) newErrors.yearOfStudy = 'Year of Study is required.';

    const emailRegex = /\S+@\S+\.\S+/;
    if (!email) {
      newErrors.email = 'Email is required.';
    } else if (!emailRegex.test(email)) {
      newErrors.email = 'Please provide a valid email address.';
    }

    const phoneRegex = /^\d{10}$/;
    if (!phone) {
      newErrors.phone = 'Phone number is required.';
    } else if (!phoneRegex.test(phone)) {
      newErrors.phone = 'Phone number must be exactly 10 digits.';
    }

    const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
    if (!password) {
      newErrors.password = 'Password is required.';
    } else if (!passwordRegex.test(password)) {
      newErrors.password = 'Password must be at least 8 characters long and include an uppercase letter, a lowercase letter, a number, and a special character.';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validate()) {
      showError('Please fix the validation errors before submitting.', 'Validation Error');
      return;
    }
    setLoading(true);
    clearMessage();
    
    try {
      const response = await api('/api/admin/create-student', {
        method: 'POST',
        body: formData,
      });

      if (response.success) {
        showSuccess('Student account created successfully and is now available in the system.', 'Student Created');
        onStudentCreated(response.student);
        // Close modal after a short delay to show success message
        setTimeout(() => {
          onClose();
        }, 1500);
      } else {
        showError(response.message || 'Failed to create student account. Please try again.', 'Creation Failed');
      }
    } catch (error) {
      console.error('Create student error:', error);
      const errorMessage = getMessage('user', 'create', error.message, { userType: 'Student' });
      showError(errorMessage, 'Creation Failed');
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50">
      <div className="bg-white rounded-lg p-8 w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        <h2 className="text-2xl font-bold mb-6">Create New Student</h2>
        <p className="text-sm text-gray-600 mb-4">
          <strong>Note:</strong> Student ID will be automatically generated by the system.
        </p>
        
        {/* Professional Message Display */}
        <MessageDisplay
          show={message.show}
          type={message.type}
          title={message.title}
          message={message.message}
          onClose={clearMessage}
          className="mb-4"
        />
        
        <form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {/* Form fields */}
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Username</label>
            <input type="text" name="username" value={formData.username} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
            {errors.username && <p className="text-red-500 text-xs mt-1">{errors.username}</p>}
          </div>
          {/* Student ID will be auto-generated by the system */}
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Student Name</label>
            <input type="text" name="studentName" value={formData.studentName} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
            {errors.studentName && <p className="text-red-500 text-xs mt-1">{errors.studentName}</p>}
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">First Name</label>
            <input type="text" name="firstName" value={formData.firstName} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
            {errors.firstName && <p className="text-red-500 text-xs mt-1">{errors.firstName}</p>}
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Last Name</label>
            <input type="text" name="lastName" value={formData.lastName} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
            {errors.lastName && <p className="text-red-500 text-xs mt-1">{errors.lastName}</p>}
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Email</label>
            <input type="email" name="email" value={formData.email} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
            {errors.email && <p className="text-red-500 text-xs mt-1">{errors.email}</p>}
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Phone</label>
            <input type="text" name="phone" value={formData.phone} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
            {errors.phone && <p className="text-red-500 text-xs mt-1">{errors.phone}</p>}
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Password</label>
            <input type="password" name="password" value={formData.password} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
            {errors.password && <p className="text-red-500 text-xs mt-1">{errors.password}</p>}
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Institute</label>
            <CollegeDropdown
              id="institute"
              value={formData.institute}
              onChange={handleCollegeChange}
              error={errors.institute}
            />
            {errors.institute && <p className="text-red-500 text-xs mt-1">{errors.institute}</p>}
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Course</label>
            <input type="text" name="course" value={formData.course} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
            {errors.course && <p className="text-red-500 text-xs mt-1">{errors.course}</p>}
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Major</label>
            <input type="text" name="major" value={formData.major} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
            {errors.major && <p className="text-red-500 text-xs mt-1">{errors.major}</p>}
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Year of Study</label>
            <input type="text" name="yearOfStudy" value={formData.yearOfStudy} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
            {errors.yearOfStudy && <p className="text-red-500 text-xs mt-1">{errors.yearOfStudy}</p>}
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Date of Birth</label>
            <input type="date" name="dob" value={formData.dob} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Gender</label>
            <select name="gender" value={formData.gender} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm">
              <option value="">Select Gender</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
              <option value="Other">Other</option>
            </select>
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Address</label>
            <input type="text" name="address" value={formData.address} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Landmark</label>
            <input type="text" name="landmark" value={formData.landmark} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">Zipcode</label>
            <input type="text" name="zipcode" value={formData.zipcode} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">City</label>
            <input type="text" name="city" value={formData.city} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
          </div>
          <div className="mb-2">
            <label className="block text-sm font-medium text-gray-700">District</label>
            <input type="text" name="district" value={formData.district} onChange={handleChange} className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm" />
          </div>
          <div className="col-span-1 md:col-span-2 flex justify-end gap-4 mt-4">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 bg-gray-200 text-gray-800 rounded-md hover:bg-gray-300"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 disabled:bg-indigo-300"
            >
              {loading ? 'Creating...' : 'Create Student'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateStudentModal;
